# The workflow name
# The workflow name
name: Check

# Definition of the workflow trigger
on:
  push:
    branches: main
  pull_request:
    branches: main

# The job definition itself
jobs:
  build:
    strategy:
      matrix:
        # Version of nodeJS we would like to build on
        version: [18, 20]
    # The runner machine system
    runs-on: ubuntu-latest

    # Commands to be executed
    steps:
      - uses: actions/checkout@v3 # Checkout action - fetching repository contents
      - name: Use Node.js ${{ matrix.node-version }} # step name
        # the ${{ matrix.node-version }} is defined in the version array above
        uses: actions/setup-node@v4 # Action providing NodeJS to our ubuntu runner
        with: # parameters to the actions/setup-node@v4 based on the version array
          node-version: ${{ matrix.node-version }}
      # The commands to be run
      # Equivalent of npm install but it uses package-lock,
      # so the libs versions will be exactly the same as in the last "npm i" run
      - run: npm ci
      - run: npm run lint # Run linter
      - run: npm run build # Run app build